config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'
  get 'timetable', to: 'pages#timetable'
  get 'joinus', to: 'pages#joinus'
  get 'faqs', to: 'pages#faqs'
  get 'mondaywk1', to: 'pages#mondaywk1'
  get 'tuesdaywk1', to: 'pages#tuesdaywk1'
  get 'wednesdaywk1', to: 'pages#wednesdaywk1'
  get 'thursdaywk1', to: 'pages#thursdaywk1'
  get 'fridaywk1', to: 'pages#fridaywk1'
  get 'mondaywk2', to: 'pages#mondaywk2'
  get 'tuesdaywk2', to: 'pages#tuesdaywk2'
  get 'wednesdaywk2', to: 'pages#wednesdaywk2'
  get 'thursdaywk2', to: 'pages#thursdaywk2'
  get 'fridaywk2', to: 'pages#fridaywk2'
  get 'mondaywk3', to: 'pages#mondaywk3'
  get 'tuesdaywk3', to: 'pages#tuesdaywk3'
  get 'wednesdaywk3', to: 'pages#wednesdaywk3'
  get 'thursdaywk3', to: 'pages#thursdaywk3'
  get 'fridaywk3', to: 'pages#fridaywk3'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @course = false
  end
  def timetable
    @course = false
  end
  def profile
    @course = true
    @user = current_user
  end
  def mondaywk1
    @course = true
  end
  def tuesdaywk1
    @course = true
  end
  def wednesdaywk1
    @course = true
  end
  def thursdaywk1
    @course = true
  end
  def fridaywk1
    @course = true
  end
  def mondaywk2
    @course = true
  end
  def tuesdaywk2
    @course = true
  end
  def wednesdaywk2
    @course = true
  end
  def thursdaywk2
    @course = true
  end
  def fridaywk2
    @course = true
  end
  def mondaywk3
    @course = true
  end
  def tuesdaywk3
    @course = true
  end
  def wednesdaywk3
    @course = true
  end
  def thursdaywk3
    @course = true
  end
  def fridaywk3
    @course = true
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    flash.clear
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_bottombar.html.erb
 <div class="bottombar">
  <div class="bartext">
  <a class="active" href="#home">Contact Us</a>
  <a href="#news">Info</a>
  <a href="#contact">Work For Us</a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
 <div class="topnav">
  <%= link_to profile_path do %>
  <div>
  <%= image_tag('profile-image', class:'profile-image') %>
  </div>
  <% end %>
  <%= link_to root_path do %>
  <div>Home</div>
  <% end %>
  <%= link_to timetable_path do %>
  <div>The Course</div>
  <% end %>
  <%= link_to faqs_path do %>
  <div>FAQs</div>
  <% end %>
  <%= link_to new_user_session_path do %>
  <div>Login</div>
  <% end  %>
</div>

app/views/layouts/_sidebar.html.erb
 <div id="mySidenav" class="sidenav">
  <div class="subnav">
  <a class="subnavbtn" href="#">Week 1 <i class="fa fa-caret-down"></i></a>
    <div class="subnav-content">
      <%= link_to "Monday", mondaywk1_path %>
      <%= link_to "Tuesday", tuesdaywk1_path %>
      <%= link_to "Wednesday", wednesdaywk1_path %>
      <%= link_to "Thursday", thursdaywk1_path %>
      <%= link_to "Friday", fridaywk1_path %>
    </div>
  </div>
    <div class="subnav">
    <a class="subnavbtn" href="#">Week 2 <i class="fa fa-caret-down"></i></a>
    <div class="subnav-content">
      <%= link_to "Monday", mondaywk2_path %>
      <%= link_to "Tuesday", tuesdaywk2_path %>
      <%= link_to "Wednesday", wednesdaywk2_path %>
      <%= link_to "Thursday", thursdaywk2_path %>
      <%= link_to "Friday", fridaywk2_path %>    </div>
  </div>
    <div class="subnav">
    <a class="subnavbtn" href="#">Week 3 <i class="fa fa-caret-down"></i></a>
    <div class="subnav-content">
      <%= link_to "Monday", mondaywk3_path %>
      <%= link_to "Tuesday", tuesdaywk3_path %>
      <%= link_to "Wednesday", wednesdaywk3_path %>
      <%= link_to "Thursday", thursdaywk3_path %>
      <%= link_to "Friday", fridaywk3_path %>
    </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Theareschool</title>

    <link rel="stylesheet" href="https://use.typekit.net/lja7lai.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;300;400;600&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <%= render "layouts/navbar" %>

    <body>
    <%= yield %>
    </body>
    <%= render "layouts/bottombar" %>
    <%= render "layouts/sidebar" if @course %>
</html>

app/views/pages/faqs.html.erb
<div class="faqs">
  <h1 class="faqstitle">
    FAQs
  </h1>
  <h2 class="faqssub">
    What do I need to complete this course
  </h2>
  <p class='faqstext'>
    This course is priced considerably cheaper than 99% of high level performing arts training courses in an effort for us make this kind of training available for as many people as possible. One of the biggest ways we help to keep the cost down is avoiding paying out for studio hire. Therefore each student will need a good wifi, a laptop or ipad, zoom downloaded and a small amount of space capable of completing dance routines and fitness classes.
  </p>
  <h2 class="faqssub">
    Is your course available worldwide?
  </h2>
  <p class="faqstext">
    Our course is made to be as accesible and affordable as possible, offering west end and broadway level tuition to anyone and therefore can be taken by ANYONE, ANYWHERE. Each day we have live classes which we encourage our students to take part in live, allowing for fluctuations in time difference. However, huge amounts of the coursework, pre recorded material and challenges are available online to be completed at any time. Students are also partnered with a teaching assistant to support schedule management and progress along the course.
  </p>
  <h2 class="faqssub">
    Is your course safe?
  </h2>
  <p class="faqstext">
    Our team is entirely DBS checked, and have all taken part in online safety workshops to ensure the safety of staff and students taking part in our course. We take the wellbeing of our students extremely seriously, so much so that all students take part in a mental health/wellness and the arts workshop to help introduce safe practices within the first steps of this career.
  </p>
</div>

app/views/pages/fridaywk2.html.erb
<div class="coursemain">
  <div class="titlebox">
  <h1 class="coursetitle">FRIDAY</h1>
  <h1 class="weektitle">WEEK TWO</h1>
  </div>

    <div class="subnav1">
    <a class="subnavbtn1" href="#">Watch and complete stretch video (30 mins)  <i class="fa fa-caret-down"></i></a>
    <div class="line"></div>
    <div class="subnav-content1">
      <div class="videobox">
      <p class='subnavtext-vid'>This 30 min stretch video is designed to warm up your muscles, begin to increase your flexiblity and introduce standard exercises used by schools.
Even if dance isn’t your strong suit, drama schools are looking a willingness to learn and someone is teachable!
Find some space, grab some water and work through this video to start your day.</p>
    <div class="inlinevid"><%= image_tag('youtubeimg', class:"vid") %></div>
    </div>
    </div>
  </div>

  <div class="subnav1">
    <a class="subnavbtn1" href="#">Masterclass! (1 hour) <i class="fa fa-caret-down"></i></a>
    <div class="line"></div>
    <div class="subnav-content1">
      <p class='subnavtext'>We are so excited to bring you the first masterclass, with Lorem ipsum dolor, sit amet consectetur adipisicing, elit.
      <br>
       Porro nemo enim, libero consequatur? Iusto impedit, vel dolore illum aperiam ducimus quidem quaerat officiis suscipit saepe culpa veritatis facilis sint iste?</p>
      <h5>
       ZOOM LINK
       </h5>
    </div>
  </div>

  <div class="subnav1">
      <a class="subnavbtn1" href="#">Audition Technique Group Class (30 mins)  <i class="fa fa-caret-down"></i></a>
      <div class="line"></div>
      <div class="subnav-content1">
        <p class='subnavtext'>First group meeting to talk through some basics of audition technique, what to and not to do and how to put your best foot forward in the scary world of auditions!
    </p>
    <br>
    <h5>
       ZOOM LINK
    </h5>
    </div>
  </div>


</div>

app/views/pages/fridaywk3.html.erb
<div class="coursemain">
  <div class="titlebox">
  <h1 class="coursetitle">FRIDAY</h1>
  <h1 class="weektitle">WEEK THREE</h1>
  </div>
  <div class="subnav1">
      <a class="subnavbtn1" href="#">Final Performance! (30 mins)  <i class="fa fa-caret-down"></i></a>
      <div class="line"></div>
      <div class="subnav-content1">
        <p class='subnavtext'>
  Today you’re going to perform both songs and both monologues for the rest of the class.
  <br><br>
  You have come so far, on behalf of all the staff we want to thank you for your hard work, now go and smash your audition and we hope to see you onstage in the not so distant future.
</p>
</div>
</div>
</div>

app/views/pages/home.html.erb
<div class="all">

  <div class="pt1">

  <div class='hometext'>

  <h1 class='title'>
    NEXT GEN
    <br>
    THEATRE
  </h1>
  <h2 class='subtitle'>Nail your drama school audition with our 3 week intensive
  <br>
  to help prepare you for the first step in your career.</h2>
  </div>
  </div>

  <div class="pt2">
    <h1 class="pt2heading">SOUND FAMILIAR?</h1>
    <ul class="pt2list">
      <li>
        <p>Want to go to drama school but don’t know where to start?</p>
      </li>
      <li>
        <p>No idea where to find audition materials/cuts
        </p>
      </li>
      <li>
        <p>Love performing but overwhelmed by the choice of schools?
        </p>
      </li>
    </ul>
    <ul class="pt2list2">
      <li>
        <p>Don’t know what monologue/song to perform?</p>
      </li>
      <li>
        <p>Want to improve but live too far from high quality training?
        </p>
      </li>
      <li>
        <p>Can’t afford the £500+ a week training from other schools?
        </p>
      </li>
    </ul>
    <button class='pt2button'>
      <p class="buttontext">Join Us</p>
    </button>
  </div>

  <div class="pt3">
  <h1 class='pt3title'>THE COURSE</h1>
  <br>
  <div class='pt3text'>
    <p>
      We provide the world’s first professionally led online intensive pre drama
      school musical theatre course. Learn direct from Broadway + West End Professionals
      with our technology led approach to foundation theatre education.
    </p>
  <ul>
    <li>Live 1-1 tuition with world class teachers</li>
    <li>Pre-recorded workshops.</li>
    <li>Live group training.</li>
    <li>Personally tailored coursework and challenges.</li>
  </ul>
    <p>
    Plus Masterclasses from some of leading figures in the world of TV, film, and theatre as
    well as teaching and audition panel staff from the top drama schools in the world.
    </p>

  </div>
  <button class='pt3button'>
      <p class="buttontext">Book your spot</p>
    </button>
  </div>
</div>

<div class="pt4">
  <div class="pt4box">
    <h2 class="boxtitle">
      What our students say about us
    </h2>
    <br>
    <div class="boxquotes">
      <p class="boxquote1">
        ‘I loved it, the course assistants helped me stay disciplined and on track. I found the pre recorded classes great to do before I left for work on a sunday’. James
      </p>
      <p class="boxquote2">
        ‘I thought I knew where I wanted to go for college, but after working through the Next Gen course I was able to come up with five courses that suited my career plan better than my original choice.’ Kwame
      </p>
      <p class="boxquote2">
        I’m based nowhere near the big courses in London so to work with these teachers without having to travel for hours was the main attraction to me.’ Alicia
      </p>
    </div>
  </div>
</div>
<div class="pt5">
  <h1 class= "pt5title">ABOUT US </h1>
  <br>
  <h2 class="pt5sub">Next Gen theatre was created by industry leading professionals with a fundamental goal - to use technology to improve the accesibility, affordability and quality of theatre tuition throughout the world.</h2>
  <div class="pt5teacher1">
    <img src="" alt="" class="robimg">
    <div class="teacherbox">
    <h2 class="teachertitle">Robert Colvin</h2>
    <h3 class="teachersub">Founder and Course Leader</h3>
    <p class="teacherbio">Robert Colvin is an actor, singer and dancer who was performed across the world including stints on broadway, the west end and across Europe, America, Asia in shows including The Book Of Mormon, Dirty Dancing, Legally Blonde, Thoroughly Moden Millie, Grease, Joseph and many more.</p>
    </div>
  </div>
  <div class="pt5teacher1">
    <img src="" alt="" class="austinimg">
    <div class="teacherbox">
    <h2 class="teachertitle">Austin Wilks</h2>
    <h3 class="teachersub">Co-Founder and Head of Content</h3>
    <p class="teacherbio">Austin Wilks has been working as a dancer and performer for the past 15 years and has recently moved in to the world of choreography, working as choreographer on the hit west end show Dirty Dancing at London’s Dominion Theatre, as well as this he runs</p>
    </div>
  </div>
</div>

app/views/pages/mondaywk1.html.erb
<div class="coursemain">
  <div class="titlebox">
  <h1 class="coursetitle">MONDAY</h1>
  <h1 class="weektitle">WEEK ONE</h1>
  </div>
  <div class="subnav1">
      <a class="subnavbtn1" href="#">Work through monologue exercise (30 mins)  <i class="fa fa-caret-down"></i></a>
      <div class="line"></div>
      <div class="subnav-content1">
        <p class='subnavtext'>Your task today is to find three potential monologues, this should take a few hours! Email your selections to submission@nexgen.com. We will review your selections, and point you in the right direction if needs be. This is a super important task, as we will eventually narrow this down to two which will be your two monologues for your drama school auditions! Your deadline for this is Thursday.
          <br><br>
          Finding monologues is a continuous struggle for professional actors so get used to this! Finding one suits you just right, that you can get in to easily, that allows you to show off and isn’t done by every other person auditioning is a hard ask.  With our help and assistance from your 1-1 lessons we will demystify the process and help you find the perfect monologue to show your strengths as an actor and help you smash this section of the audition process. As well as getting you used to this process so you can do it when you are finished with the course.
          <br><br>
          1. Look through our library of monologues to see if there is anything there that takes your fancy, or interests you.  Other resources to look through - https://www.themonobox.co.uk/monolibrary - https://www.dailyactor.com/monologues - http://www.monologuearchive.com/ - http://www.monologuedb.com/  Look for characters who are the same casting as you, same sort of age and same accent as you. In a drama school audition the panel want to see you - whilst it may be tempting to show off an accent, try not to go too far out ‘the box’ and only ever do an accent if you are able to aptly portray a native - there is nothing worse than an audition with a dodgy, or even ok accent, this can take the focus away from your acting ability and stop the panel from seeing how good you are.  Try wherever possible to make your monologue entertaining as opposed to hard-hitting, extremely deep monologues. You will always get further with a well done cheerful, pleasant monologue over a badly done monologue with loads of shouting, crying or swearing. It can be tempting to demonstrate how good you are by showing extremity of emotion, but as you will find as your career progresses it is 100x harder to produce a natural, believable performance that shows what you can do over shouting and screaming at an audition panel.

      </div>
  </div>
  <div class="subnav1">
    <a class="subnavbtn1" href="#">Watch and complete stretch video (30 mins)  <i class="fa fa-caret-down"></i></a>
    <div class="line"></div>
    <div class="subnav-content1">
      <div class="videobox">
      <p class='subnavtext-vid'>This 30 min stretch video is designed to warm up your muscles, begin to increase your flexiblity and introduce standard exercises used by schools.
Even if dance isn’t your strong suit, drama schools are looking a willingness to learn and someone is teachable!
Find some space, grab some water and work through this video to start your day.</p>
    <div class="inlinevid"><%= image_tag('youtubeimg', class:"vid") %></div>
    </div>
    </div>
  </div>
  <div class="subnav1">
    <a class="subnavbtn1" href="#">Attend live jazz class (1 hour)  <i class="fa fa-caret-down"></i></a>
    <div class="line"></div>
    <div class="subnav-content1">
      <p class='subnavtext'>Today you have your first live class with renowed choreographer and teacher, Austin Wilks. Austin is the choreographer of Dirty Dancing in the West End as well having performed and taught all over the world.
This class will be focused on basic jazz skills, followed by choreography - remember you can only give your best and always remember to use your face when dancing!</p>
      <h5>
       ZOOM LINK
       </h5>
    </div>
  </div>

</div>

app/views/pages/mondaywk2.html.erb
<div class="coursemain">
  <div class="titlebox">
  <h1 class="coursetitle">MONDAY</h1>
  <h1 class="weektitle">WEEK TWO</h1>
  </div>

  <div class="subnav1">
      <a class="subnavbtn1" href="#">Learn Monologue! (30 mins)  <i class="fa fa-caret-down"></i></a>
      <div class="line"></div>
      <div class="subnav-content1">
        <p class='subnavtext'>Simple task today, I want you to use this thirty minutes to begin learning one of your monologues. This task requires discipline!  Ultimately, in this industry if you want to go far you have to be super disciplined. Support from teachers, parents, friends will only get you so far - you are the only person who determines how far you can go in the industry and one of the key factors that regulates this is your ability to be self-disciplined. So, let’s test it. See, how far you can get with learning the first of your monologues. If this task is your idea of hell, unfortunately this is very much a part of life as a performer.

Recall audition for a west end show, you are required to learn the lines off by heart, overnight (oh and you’re currently touring in Newcastle on your current show so only have from the show finishing at 10pm, and your 3hr train ride in to London at 7:30am to learn it, and you still want to get 8 hours sleep as you will have to pick up and learn choreography as well - true story!).
    </p>
  </div>
</div>

<div class="subnav1">
      <a class="subnavbtn1" href="#">Fitness Class (30 mins)  <i class="fa fa-caret-down"></i></a>
      <div class="line"></div>
      <div class="subnav-content1">
        <div class="videobox">
        <p class='subnavtext-vid'>Fitness time! Get some water, get your game face on and lets get fit.
          <br>
        SUPER, SUPER IMPORTANT REMINDER...fitness classes are NOT about changing the way you look, ultimately musical theatre
        requires physical adeptness.
        <br>
        PERFORMERS ARE ATHLETES.
        <br>
        Regardless of your fitness level, getting to a point where you're
        comfortable pushing yourself physically is so, so important. As someone who has made his way through 8 hour audition days,
        with relentless hours of physical work - dirty dancing dance call with Austin for example - I can tell you it is essential
        and drama schools will look to see that you can push yourself physically!
        <br>
        Smash it!
        </p>
      <div class="inlinevid"><%= image_tag('youtubeimg', class:"vid") %></div>
      </div>
      </div>
    </div>

    <div class="subnav1">
    <a class="subnavbtn1" href="#">Attend live MT jazz class (1 hour)  <i class="fa fa-caret-down"></i></a>
    <div class="line"></div>
    <div class="subnav-content1">
      <p class='subnavtext'>Today you have your first live class with renowed choreographer and teacher, Austin Wilks. Austin is the choreographer of Dirty Dancing in the West End as well having performed and taught all over the world.
This class will be focused on basic jazz skills, followed by choreography - remember you can only give your best and always remember to use your face when dancing!</p>
      <h5>
       ZOOM LINK
       </h5>
    </div>
  </div>

</div>

app/views/pages/profile.html.erb
<!-- Use any element to open the sidenav -->

<!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->
<div id="main">
  <div class="profilesection">
  <h1 class="proftitle">Hi <%= "#{current_user.first_name}"%></h1>

<%= image_tag('profile-image', class:'profile-image2') %>
<% require 'time'
date = Date.today.wday    # fourth day of the week.
date = Date::DAYNAMES[Date.today.wday]   %>

<h3 class="group">Group 1</h3>
<h4 class="groupdates">February 4th-31st '22</h4>
<p class='date'>Today is <%= date %></p>
</div>


  <%= link_to edit_user_registration_path do %>
  <div class="edit">
  <h2>Complete your profile</h2>
  </div>
  <% end  %>
</h1>





</div>

app/views/pages/tuesdaywk1.html.erb
<div class="coursemain">
  <div class="titlebox">
  <h1 class="coursetitle">TUESDAY</h1>
  <h1 class="weektitle">WEEK ONE</h1>
  </div>
  <div class="subnav1">
      <a class="subnavbtn1" href="#">Private Singing Lesson (30 mins)  <i class="fa fa-caret-down"></i></a>
      <div class="line"></div>
      <div class="subnav-content1">
        <p class='subnavtext'>
          You should have now been given your one-to-one singing slot with our expert singing teacher.
          Together you will work to improve fundamentals of singing technique as well as selecting a bulletproof audition song
          to smash your audition and help put you in the position to kick start your career.
          <br>
          Things to remember - hydrate, relax, have fun!
        </p>
      </div>
  </div>

  <div class="subnav1">
      <a class="subnavbtn1" href="#">Work through monologue exercise (30 mins)  <i class="fa fa-caret-down"></i></a>
      <div class="line"></div>
      <div class="subnav-content1">
        <p class='subnavtext'>Your acting task for today is to find your first monologue!
    This may sound like a super easy task, however there is so much to take in account when choosing a monologue so I want you to answer IN DEPTH these questions. Each answer should be around 5-6 lines minimum.
    <br>
    1. Why do I like this monologue? What about this monologue attracts me to it/makes me want to perform it. <br>
    2. Is this monologue right for me? Is the character similar to me? Can I relate to what they are going through or describing? <br>
    3. Where is the monologue from? Playwright, Author? Who performed it originally? What is the play called? <br>
    4. Describe the character. Where are they from? What do they look like? Describe them in detail. <br>
    5. Context? What has just happened to the character before this moment? <br>
    </p>
      </div>
  </div>
</div>